version: '3'

services:
  couchbase:
    image: couchbase/server:latest
    ports:
      - "8091:8091"
      - "8092:8092"
      - "11210:11210"
    environment:
      - couchbase_user=Никита
      - couchbase_password=п12345
